name: Deploy Power Platform Solution (Username/Password)

# Trigger the workflow on pushes to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate to Power Platform using username/password
      - name: Authenticate to Power Platform
        run: |
          pac auth create --url ${{ secrets.PP_ENV_URL }} --username ${{ secrets.PP_USERNAME }} --password ${{ secrets.PP_PASSWORD }}

      # Step 3: Import Power Platform solution
      - name: Import Solution
        run: |
          pac solution import --path ./TaskApp_1_0_0_1.zip --overwrite true

      # Step 4: Optional: list imported solutions for confirmation
      - name: List Solutions
        run: |
          pac solution list
