name: Deploy Power Platform Solution (Username/Password)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Power Platform CLI
        run: npm install -g pac

      - name: Authenticate to Power Platform
        run: |
          pac auth create --url ${{ secrets.PP_ENV_URL }} --username ${{ secrets.PP_USERNAME }} --password ${{ secrets.PP_PASSWORD }}
      
      - name: Import Solution
        run: |
          pac solution import --path ./TaskApp_1_0_0_1.zip --overwrite true
