name: Deploy Power Platform Solution (Username/Password)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Download Power Platform CLI
      - name: Download Power Platform CLI
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/PowerPlatformCLI-Win-x64" -OutFile "pac.zip"
          Expand-Archive -LiteralPath pac.zip -DestinationPath ./pac
          $env:PATH = "$env:PATH;$(Resolve-Path ./pac)"

      # 3. Authenticate to Power Platform
      - name: Authenticate to Power Platform
        run: |
          pac auth create --url ${{ secrets.PP_ENV_URL }} --username ${{ secrets.PP_USERNAME }} --password ${{ secrets.PP_PASSWORD }}

      # 4. Import solution
      - name: Import Solution
        run: |
          pac solution import --path ./TaskApp_1_0_0_1.zip --overwrite true

      # 5. Optional: list solutions
      - name: List Solutions
        run: |
          pac solution list
